### ISSUE TITLE
Put Lua improvements on the shelf for now due to stupid mistake

### ISSUE THREAD

**Issue by DJLevel3** [DJLevel3/osci-render-vst3port#1]
Well, I'm an idiot. I ran `git pull` without committing changes first. About 90% of my progress has been lost, so I'm going to put the Lua improvements on hold for now while I work on easier changes. I had made some stupid decisions anyway, so it's not like I'm devastated by this, but I don't want to restart this big project for now.

In the meantime, I'm going to resume work on the Blender frame baking project. I have a great idea as to how I want to implement it, and it shouldn't take nearly as much effort as rewriting the Lua functionality.

**Comment by jameshball** [comment]
Sorry to hear that 😭 classic mistake that we all learn that hopefully won't happen again haha.

Blender baking sounds good! Let me know how it goes :)

**Comment by DJLevel3** [comment]
Well, I had the repo in another folder that was up to date! Yay! I'm still shelving it for now as I have no motivation anymore, but my good changes remain intact.
